spring:
  # \u914D\u7F6ErabbitMQ\u670D\u52A1\u5668
  rabbitmq:
    host: 192.168.20.149
    port: 5672
    username: admin
    password: 123456
    # \u865A\u62DF\u4E3B\u673A
    virtual-host: spring-boot