spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://192.168.20.145:3306/JPA?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

knife4j:
  enable: true

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    root: info

# WEB 配置
server:
  port: 8080
  servlet:
    context-path: /springjpa
    session:
      timeout: 60